version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /python-project/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /python-project/docker-credentials/password
    DOCKER_REGISTRY_URL: /python-project/docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Building Docker Image"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/python-project-app:latest" .
      - docker push "docker.io/shashi2002/python-project-app:latest"
  post_build:
    commands:
      - echo "Build is Successful"
artifacts:
  files:
    - '**/*'
  base-directory: .
